version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    volumes:
      - ./backend/:/code/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    volumes:
      - ./frontend/:/code/
    command: npm start
    ports:
      - 3000:3000
